# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/ktexteditor': '@stable'
    'frameworks/kio': '@stable'
    'pim/kitinerary': '@same'
