# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'Windows/Qt5', 'Android/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/ktexteditor': '@stable'
    'frameworks/kio': '@stable'
    'pim/kitinerary': '@same'
- 'on': ['Linux/Qt6', 'FreeBSD/Qt6', 'Windows/Qt6', 'Android/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/ktexteditor': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'pim/kitinerary': '@latest-kf6'
