# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows', 'Android']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/ktexteditor': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/kcolorscheme': '@latest-kf6'
    'pim/kitinerary': '@latest-kf6'

Options:
  require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
